"""Add advanced portal fields

Revision ID: 2023c8e0ed03
Revises: d8c66e7723e1
Create Date: 2026-04-15 20:55:29.010967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2023c8e0ed03'
down_revision = 'd8c66e7723e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('min_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_boosted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('job_swipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ats_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_rank_score', sa.Float(), nullable=True))

    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_preference', sa.String(length=50), nullable=True))
        batch_op.drop_column('shift')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('shift_preference')

    with op.batch_alter_table('job_swipes', schema=None) as batch_op:
        batch_op.drop_column('ai_rank_score')
        batch_op.drop_column('match_score')
        batch_op.drop_column('ats_score')

    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_column('is_boosted')
        batch_op.drop_column('tags')
        batch_op.drop_column('min_experience')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('max_salary')

    # ### end Alembic commands ###
