"""Added fields

Revision ID: 389215b5d97d
Revises: 
Create Date: 2026-04-28 11:00:44.175667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389215b5d97d'
down_revision = '001_full_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('desired_roles', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('salary_expectation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('salary_expectation')
        batch_op.drop_column('desired_roles')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
