"""Add interview tracking and hiring fields to JobSwipe

Revision ID: d5d40e8b7f56
Revises: add_missing_employer_columns
Create Date: 2026-06-01 13:20:59.441147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d40e8b7f56'
down_revision = 'add_missing_employer_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('number_of_positions')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user'), ['user_id', 'user_type'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_positions', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))

    # ### end Alembic commands ###
