"""added seeker advanced fields

Revision ID: d8c66e7723e1
Revises: 377390de7183
Create Date: 2026-04-15 20:31:07.421715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c66e7723e1'
down_revision = '377390de7183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('experience_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('career_field', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('job_location_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shift', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.drop_column('shift')
        batch_op.drop_column('job_location_type')
        batch_op.drop_column('job_status')
        batch_op.drop_column('career_field')
        batch_op.drop_column('experience_type')
        batch_op.drop_column('dob')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
