"""Add job_location_type to listing

Revision ID: de762b77d87c
Revises: 2023c8e0ed03
Create Date: 2026-04-15 20:56:02.950242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de762b77d87c'
down_revision = '2023c8e0ed03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_location_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_column('job_location_type')

    # ### end Alembic commands ###
